name: Sync to Hugging Face

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dataset: [go-epic, caia-math, caia-system-design, cicd-epic, python-epic, rust-epic]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install huggingface-hub
        run: pip install huggingface-hub
      
      - name: Create HF repository
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python3 -c "
import os
from huggingface_hub import HfApi
api = HfApi()
try:
    api.create_repo(
        repo_id='CaiaTech/${{ matrix.dataset }}',
        token=os.environ['HF_TOKEN'],
        repo_type='dataset',
        exist_ok=True
    )
    print('Repository created or already exists')
except Exception as e:
    print(f'Error: {e}')
    exit(1)
"
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir -p /tmp/hf-dataset
          
          if [ -f "${{ matrix.dataset }}/${{ matrix.dataset }}.jsonl" ]; then
            cp "${{ matrix.dataset }}/${{ matrix.dataset }}.jsonl" /tmp/hf-dataset/
          else
            echo "Error: Dataset file ${{ matrix.dataset }}/${{ matrix.dataset }}.jsonl not found"
            exit 1
          fi
          cp LICENSE /tmp/hf-dataset/
          
          cd /tmp/hf-dataset
          git init -b main
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
          git lfs install
          git lfs track "*.parquet"
          git lfs track "*.jsonl"
          git add .gitattributes
          
          git add .
          git commit -m "Sync from GitHub"
          
          git remote add hf https://CaiaTech:$HF_TOKEN@huggingface.co/datasets/CaiaTech/${{ matrix.dataset }}
          git push hf main --force
