name: Sync to Hugging Face

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dataset: [go-epic, caia-math, caia-system-design, cicd-epic, python-epic, rust-epic, caia-civil-rights, caia-reasoning]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install huggingface-hub
        run: pip install huggingface-hub
      
      - name: Create HF repository
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python3 -c "import os; from huggingface_hub import HfApi; api = HfApi(); api.create_repo(repo_id='CaiaTech/${{ matrix.dataset }}', token=os.environ['HF_TOKEN'], repo_type='dataset', exist_ok=True)"
      
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          mkdir -p /tmp/hf-dataset
          cp ${{ matrix.dataset }}/${{ matrix.dataset }}.jsonl /tmp/hf-dataset/
          cp ${{ matrix.dataset }}/${{ matrix.dataset }}.json /tmp/hf-dataset/
          cp ${{ matrix.dataset }}/${{ matrix.dataset }}.parquet /tmp/hf-dataset/
          if [ -f "${{ matrix.dataset }}/README.md" ]; then
            cp ${{ matrix.dataset }}/README.md /tmp/hf-dataset/
          fi
          cp LICENSE /tmp/hf-dataset/
          cd /tmp/hf-dataset
          git init -b main
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git lfs install
          git lfs track "*.jsonl"
          git lfs track "*.json"
          git lfs track "*.parquet"
          git add .gitattributes
          git add .
          git commit -m "Sync from GitHub"
          git remote add hf https://CaiaTech:$HF_TOKEN@huggingface.co/datasets/CaiaTech/${{ matrix.dataset }}
          git push hf main --force